### ISSUE TITLE
overviews/collections/maps.md

### ISSUE THREAD

**Issue by enshahar** [codeport/scala.github.com#10]

**Comment by outsideris** [comment]
엄청난 속도로 번역을 하셔서 제가 따라가기가 어렵네요.
(이럴때는 속도를 좀 받쳐줘야 힘이 나실텐데 제가 다른 일로 요즘 시간이 잘 안나네요.. ㅠ)
이슈완료하신건 풀리퀘에서 머지까지 하시는게 어떠신가요?

**Comment by enshahar** [comment]
지금 회사에서 하는일이 개발이 아니고 관리라서 비는 시간이 조금 있습니다. ^^

권한을 주시면 작업이 가능하겠죠. 첨부파일은 제 퍼블릭 키입니다.

2013/7/1 JeongHoon Byun (aka Outsider) notifications@github.com

**Comment by outsideris** [comment]
머지 권한이 없으신가요?
팀으로 머지권한을 드려서 될줄 알았는데요..

**Comment by enshahar** [comment]
어.. 시도를 안해봤어요 ^^  한번 해보고 알려드리겠습니다.

**Comment by enshahar** [comment]
머지하려면 웹에서 pull request 옆에 머지 버튼이 나타나야 하는걸텐데, 안보이네요.

리눅스박스에 클론해서 머지하고 푸시하는것도 안되고...

제가 GIT를 안써봐서 잘 모르는걸수도 있는데요, 혹시 확인 가능하시면 부탁드리겠습니다.

2013/7/3 Hyunsok Oh enshahar@gmail.com

> 어.. 시도를 안해봤어요 ^^  한번 해보고 알려드리겠습니다.
> 
> On 3 July 2013 01:12, JeongHoon Byun (aka Outsider) <

**Comment by outsideris** [comment]
[풀리퀘스트](http://d.pr/i/M49O) 에 이렇게 안나오시나요? 

[권한 설정을 이렇게](http://d.pr/i/MIhX) 하는게 아닐까요? ㅡㅡ;;

**Comment by nectarine** [comment]
저도 머지 버튼이 안뜨네요

**Comment by outsideris** [comment]
왜 안되는지 찾아보겠습니다.. 그전까지는 풀리퀘 올려주시면 제가 머지할께요.
