### ISSUE TITLE
arrays.md의 languages: [ko] 문제

### ISSUE THREAD

**Issue by enshahar** [codeport/scala.github.com#20]
헤더에 languages: [ko]를 language: ko로 바꿔야 할것 같습니다. (주의: 복수 아니고 단수입니다)

**Comment by nectarine** [comment]
수정하였습니다 ㅠㅠ

**Comment by outsideris** [comment]
a0d55cd6e 에서 수정되어 머지했으므로 이슈 닫습니다.
